---
kind: Service
apiVersion: v1
metadata:
  name: websockets
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/sessions-cookie-name: "websockets-demo"
spec:
  selector:
    app: websockets-demo
  ports:
    - name: flask
      protocol: TCP
      port: 5000
      targetPort: 5000
